steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/whatsay-api', '.']
    timeout: '1200s'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsay-api']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whatsay-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/whatsay-api'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--project'
      - '$PROJECT_ID'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:asia-south1:whatsay-db'
      - '--set-secrets'
      - 'DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/whatsay-api'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'DOCKER_BUILDKIT=1'

timeout: '1800s'
